expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    # add tls configuration
    domain: platform.dev.nuxeo.com
    exposer: Ingress
    http: true
    tlsacme: true
    tlsSecretName: platform-cluster-tls
    urltemplate: "{{.Namespace}}.{{.Domain}}"

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

nuxeo:
  fullnameOverride: nuxeo-preview
  image:
    repository: "$DOCKER_REGISTRY/nuxeo/nuxeo"
    tag: "$VERSION"
    pullSecrets:
    - name: kubernetes-docker-cfg
  podLabels:
    branch: "$BRANCH_NAME"
    team: platform
    resource: pod
    usage: "$USAGE"
  service:
    annotations:
      fabric8.io/expose: "true"
    labels:
      branch: "$BRANCH_NAME"
      team: platform
      resource: service
      usage: "$USAGE"
  mongodb:
    enabled: $PERSISTENCE
    host: "mongodb.$PREVIEW_NAMESPACE.svc.cluster.local"
  elasticsearch:
    enabled: $PERSISTENCE
    host: "elasticsearch-master.$PREVIEW_NAMESPACE.svc.cluster.local"
  persistentVolumeStorage:
    enabled: $PERSISTENCE
    size: "100Mi"
  logs:
    persistence:
      enabled: $PERSISTENCE
      size: "100Mi"
  nodeSelector:
    team: platform
  tolerations:
  - effect: NoSchedule
    key: team
    operator: Equal
    value: platform
